name: Flask CI/CD Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd ~/Portfolio_website

            git fetch --all
            git reset --hard origin/master
            git clean -fd

            ~/venv/bin/pip install -r requirements.txt

            pkill -f app.py && echo "Old Flask stopped" || echo "No Flask process"

            nohup ~/venv/bin/python ~/Portfolio_website/app.py > ~/Portfolio_website/app.log 2>&1 &