name: Flask CI/CD Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
              # Create the directory if it doesn't exist
              mkdir -p ~/Portfolio_website
              cd ~/Portfolio_website

              # Initialize git if it's a brand new folder
              if [ ! -d ".git" ]; then
                git clone https://github.com/${{ github.repository }}.git .
              fi

              git fetch --all
              git reset --hard origin/master
              git clean -fd

              # Ensure venv exists
              python3 -m venv ~/venv
              ~/venv/bin/pip install -r requirements.txt

              pkill -f app.py || true
              nohup ~/venv/bin/python app.py > app.log 2>&1 &